### ISSUE TITLE
Update on Mac

### ISSUE THREAD

**Issue by Maxoudela** [vinumeris/updatefx#12]
I've tried to use on Mac but it doesn't work. I think it's because of this code in UpdateFX

if (os.contains("mac")) {
// Returns path to the .app directory, which normally contains only a Contents directory.
List<Path> exes = Utils.listDir(appInstallDir.resolve("Contents/MacOS"));
if (exes.size() != 1)
throw new IllegalStateException("Found unknown number of app executables");
return exes.get(0);

In fact, in my "MacOS" folder I have two file, the current application and another named "libpackager.dylib". So there is not one file..

I'm running with Jdk8u40 bundled app btw

Is it normal?

**Comment by mikehearn** [comment]
That must be new in 8u40. I haven't tried with that JRE yet. If they introduced a libpackager then yeah, that bit of code will need an update.

**Comment by Maxoudela** [comment]
You are in 8 or 8u20?

**Comment by mikehearn** [comment]
I've been using 8u20. 8u31 is brand new and only focuses on serious bug fixes and security updates. 8u40 has a rewrite of the packager bootstrap tool, hence the new file.

A pull request for your fix would be appreciated, thanks!

**Comment by mikehearn** [comment]
This fix was checked in some time ago ... closing
