### ISSUE TITLE
Which JRE will be used by the updated Jar file?

### ISSUE THREAD

**Issue by fadils** [vinumeris/updatefx#19]
Let's say I'm packaging my first initial version with JRE 8u60.
Ship this version in a dmg format.

Then, a user downloads this dmg but her JRE is JRE 7.
This dmg will still work nevertheless because the runtime is already "inside" the app.

Then, there's a new update. Based on the docs, the update format is in jar format.

What happens when the user downloads this update? Which JRE will be used by this latest jar?

I mean, this code `UpdateFX.restartApp()` is basically executing a jar file. Then I'm assuming this updated version of jar will use whatever JRE installed. 
Is this correct?

**Comment by mikehearn** [comment]
It will always use the bundled JRE. Currently UpdateFX cannot upgrade the bundled JRE so you're stuck with 8u60 until the user is told to re-download the app. I'd really like that to get fixed, but I never implemented it.
