### ISSUE TITLE
Longer term: support using keys in the TREZOR for code signing

### ISSUE THREAD

**Issue by mikehearn** [vinumeris/updatefx#3]
It's unclear exactly what should be displayed on the screen for this, but a (truncated?) hash of the post-update JAR is probably right. At any rate keeping the keys inside a hardware device is an improvement even if the message on screen is a bit hard to verify.

Will wait to see how Jim/Gary get along with multibit hardware support before experimenting with this. Might be a crowdfunded project.

**Comment by mikehearn** [comment]
Done!

**Comment by ManfredKarrer** [comment]
Ah great to hear that. Will ping you some time about details...

**Comment by mikehearn** [comment]
You just specify --trezor to the updatefx app. You can also specify an argument, which is the hex encoded pubkey that should be used, to ensure there aren't any mixups.

**Comment by ManfredKarrer** [comment]
Ah cool! Will try it out for the next release!
